FROM python:3.11-slim

RUN pip install mlflow==2.9.2 psycopg2-binary boto3

EXPOSE 5000

CMD ["mlflow", "server",      "--backend-store-uri", "${MLFLOW_BACKEND_STORE_URI}",      "--artifact-root", "${MLFLOW_ARTIFACT_ROOT}",      "--host", "0.0.0.0",      "--port", "5000"]
