{
 "title": "Health Data Ingestion Dashboard",
 "description": "Dashboard for monitoring the ingestion of health data in real-time.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ingested Health Data Rate",
   "type": "stat",
   "gridPos": {
    "h": 8,
    "i": "1",
    "w": 12,
    "x": 0,
    "y": 0
   },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(health_data_ingestion_total[5m])",
     "legendFormat": "Ingested Data"
    }
   ]
  },
  {
   "title": "Total Ingestion Errors",
   "type": "graph",
   "gridPos": {
    "h": 8,
    "i": "2",
    "w": 12,
    "x": 12,
    "y": 0
   },
   "targets": [
    {
     "expr": "health_data_ingestion_errors_total",
     "legendFormat": "Ingestion Errors"
    }
   ]
  },
  {
   "title": "Ingestion Duration (95th Percentile)",
   "type": "graph",
   "gridPos": {
    "h": 8,
    "i": "3",
    "w": 12,
    "x": 0,
    "y": 8
   },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(health_data_ingestion_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile Ingestion Duration"
    }
   ]
  }
 ]
}