#!/usr/bin/env python3
"""
Free-Tier Daily MLOps Automator
=================================
Strategy:
  - GitHub Models API  → generate real code for key files (free, uses GITHUB_TOKEN)
  - Pre-written templates → bulk of remaining commits (zero API cost)
  - Conventional commit messages from 30_day_plan.json

GitHub Models API docs: https://docs.github.com/en/github-models
Free tier: ~15-50 requests/day depending on model (gpt-4o-mini is very generous).

Usage:
    python3 scripts/daily_automator_free.py --day 1 --commits 25 --plan plan/30_day_plan.json
"""

from __future__ import annotations
import argparse
import json
import os
import random
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ─────────────────────────────────────────────
# GitHub Models API client (free)
# ─────────────────────────────────────────────
GITHUB_MODELS_URL = "https://models.inference.ai.azure.com/chat/completions"
# gpt-4o-mini: very high free quota, fast, good for code
GITHUB_MODEL = "gpt-4o-mini"


def call_github_models(prompt: str, system: str, max_tokens: int = 1200) -> str | None:
    """
    Call GitHub Models API (free with GITHUB_TOKEN).
    Returns generated text or None on failure.
    """
    import urllib.request
    import urllib.error

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return None

    payload = json.dumps({
        "model": GITHUB_MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user",   "content": prompt},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.3,
    }).encode("utf-8")

    req = urllib.request.Request(
        GITHUB_MODELS_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
            return data["choices"][0]["message"]["content"].strip()
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        if "rate limit" in body.lower() or e.code == 429:
            print("  ⚠ GitHub Models rate limit hit — switching to templates")
        else:
            print(f"  ⚠ GitHub Models API error {e.code}: {body[:120]}")
        return None
    except Exception as exc:
        print(f"  ⚠ GitHub Models call failed: {exc}")
        return None


# ─────────────────────────────────────────────
# Plan loading
# ─────────────────────────────────────────────
def load_plan(plan_path: str) -> dict:
    with open(plan_path) as f:
        return json.load(f)


def get_day_plan(plan: dict, day: int) -> dict:
    for d in plan["days"]:
        if d["day"] == day:
            return d
    raise ValueError(f"Day {day} not found in plan")


def get_phase(plan: dict, day: int) -> dict:
    for phase in plan["phases"]:
        if day in phase["days"]:
            return phase
    return {}


# ─────────────────────────────────────────────
# Template fallback
# ─────────────────────────────────────────────
def get_template_content(filepath: str) -> str | None:
    """Try to import and return a pre-written template for this filepath."""
    try:
        sys.path.insert(0, str(Path(__file__).parent.parent))
        from templates.code_templates import get_template
        return get_template(filepath)
    except ImportError:
        return None


def make_stub_content(filepath: str, day_plan: dict) -> str:
    """Generate a meaningful stub when no template and no API available."""
    ext = Path(filepath).suffix
    name = Path(filepath).stem
    day = day_plan["day"]
    title = day_plan["title"]

    if ext == ".py":
        return f'''\
"""
{filepath}
Auto-generated for Day {day}: {title}
Focus: {day_plan['focus']}
"""
from __future__ import annotations
import logging

logger = logging.getLogger(__name__)

# TODO: Full implementation generated by daily automation


class {name.replace("_", " ").title().replace(" ", "")}:
    """Placeholder for {name} — implementation added in subsequent commits."""

    def __init__(self) -> None:
        logger.info("Initialising %s", self.__class__.__name__)

    def run(self) -> None:
        raise NotImplementedError("Implementation pending")
'''
    elif ext in (".yml", ".yaml"):
        return f"# {filepath}\n# Day {day}: {title}\n# Generated: {datetime.now(timezone.utc).isoformat()}\n"
    elif ext == ".json":
        return json.dumps({"day": day, "file": filepath, "title": title}, indent=2) + "\n"
    elif ext == ".md":
        return f"# {name.replace('_', ' ').title()}\n\nDay {day}: {title}\n\n{day_plan['focus']}\n"
    else:
        return f"# {filepath}\n# Day {day}: {title}\n"


# ─────────────────────────────────────────────
# Git operations
# ─────────────────────────────────────────────
def git(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(["git"] + cmd, capture_output=True, text=True)


def write_file(filepath: str, content: str) -> None:
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def append_file(filepath: str, snippet: str) -> None:
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(f"\n# {datetime.now(timezone.utc).strftime('%H:%M:%S')} — automated update\n")
        f.write(snippet + "\n")


def commit(message: str, files: list[str] | None = None) -> bool:
    if files:
        for f in files:
            git(["add", f])
    else:
        git(["add", "-A"])
    r = git(["commit", "-m", message])
    return r.returncode == 0 and "nothing to commit" not in r.stdout


# ─────────────────────────────────────────────
# Commit generation strategies
# ─────────────────────────────────────────────
SYSTEM_PROMPT = """\
You are a senior MLOps engineer building a Real-Time Smart Health Monitoring System.
Generate production-quality Python code for the requested file.
Stack: Kafka, Faust, Redis, XGBoost, PyTorch, MLflow, FastAPI, Evidently, Airflow.
Rules:
- Real runnable code — not pseudocode
- Proper imports, type hints, docstrings
- 40-120 lines
- Output ONLY raw code, no markdown fences, no explanation"""


def strategy_ai_generated(day_plan: dict, phase: dict, api_budget: int) -> int:
    """
    Use GitHub Models API to generate real code for key files.
    Returns number of commits made.
    """
    files = day_plan.get("files_to_create", [])[:api_budget]
    tasks = day_plan.get("commit_tasks", [])
    count = 0

    print(f"\n[AI] Generating code for {len(files)} files via GitHub Models (free)...")

    for i, filepath in enumerate(files):
        # 1. Try template first (instant, no quota)
        content = get_template_content(filepath)

        # 2. Fall back to GitHub Models API
        if not content:
            prompt = (
                f"Generate the file: {filepath}\n\n"
                f"Day {day_plan['day']}: {day_plan['title']}\n"
                f"Focus: {day_plan['focus']}\n"
                f"Other files today: {', '.join(day_plan.get('files_to_create', [])[:4])}"
            )
            content = call_github_models(prompt, SYSTEM_PROMPT, max_tokens=1000)

        # 3. Fall back to stub
        if not content:
            content = make_stub_content(filepath, day_plan)

        write_file(filepath, content)

        msg = tasks[i] if i < len(tasks) else f"feat: implement {Path(filepath).stem}"
        if commit(msg, [filepath]):
            count += 1
            src = "template" if get_template_content(filepath) else "ai"
            print(f"  ✓ [{count}] ({src}) {msg[:65]}")

        time.sleep(0.5)  # Be gentle with the API

    return count


def strategy_task_commits(day_plan: dict, already_done: int, target: int) -> int:
    """
    Make commits for remaining task descriptions from the plan (template-based).
    """
    tasks = day_plan.get("commit_tasks", [])[already_done:]
    refactors = day_plan.get("refactor_fix_commits", [])
    all_tasks = tasks + refactors
    files = day_plan.get("files_to_create", [])
    count = 0
    remaining = target - already_done

    print(f"\n[Templates] Making {min(len(all_tasks), remaining)} task-based commits...")

    for msg in all_tasks[:remaining]:
        if not files:
            break
        fp = random.choice(files)
        path = Path(fp)
        if not path.exists():
            write_file(fp, make_stub_content(fp, day_plan))

        # Small meaningful change
        change_type = msg.split(":")[0] if ":" in msg else "chore"
        snippet = _generate_snippet(change_type, path.stem, msg)
        append_file(fp, snippet)

        if commit(msg, [fp]):
            count += 1
            print(f"  ✓ [{already_done + count}] {msg[:70]}")

    return count


def strategy_filler(already_done: int, target: int, day: int, day_plan: dict) -> int:
    """
    Filler commits (style/docs/chore) to reach the exact target.
    Uses only local file modifications — zero API calls.
    """
    remaining = target - already_done
    if remaining <= 0:
        return 0

    print(f"\n[Filler] Making {remaining} filler commits...")

    all_py = [str(f) for f in Path("src").rglob("*.py")] if Path("src").exists() else []
    all_test = [str(f) for f in Path("tests").rglob("*.py")] if Path("tests").exists() else []
    all_files = (all_py + all_test) or day_plan.get("files_to_create", ["src/__init__.py"])

    filler_msgs = [
        "style: run black formatter on {m}",
        "fix: remove unused import in {m}",
        "docs: add module docstring to {m}",
        "refactor: extract magic number to named constant in {m}",
        "chore: add logging statement to {m}",
        "fix: handle None input edge case in {m}",
        "style: reorder imports alphabetically in {m}",
        "test: add assertion for return type in {m}",
        "perf: add __slots__ to reduce memory in {m}",
        "docs: update example in docstring of {m}",
        "fix: correct off-by-one in {m}",
        "refactor: rename variable for clarity in {m}",
        f"chore: day {day} maintenance sweep",
        "ci: update step name for readability",
        "docs: fix typo in inline comment in {m}",
    ]

    count = 0
    while count < remaining:
        fp = random.choice(all_files)
        m = Path(fp).stem
        msg = random.choice(filler_msgs).format(m=m)
        snippet = f"# {msg} — {datetime.now(timezone.utc).strftime('%H:%M:%S UTC')}"
        append_file(fp, snippet)
        if commit(msg, [fp]):
            count += 1

    return count


def _generate_snippet(commit_type: str, module: str, context: str) -> str:
    """Return a small Python snippet appropriate for the commit type."""
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    snippets = {
        "fix": f"# fix applied at {ts}\n_FIXED = True  # {context[:60]}",
        "refactor": f"# refactor: {context[:60]}\n_REFACTORED = True",
        "test": f"# test marker: {context[:60]}\n_TEST_MARKER = '{module}'",
        "perf": f"# perf improvement at {ts}\n_CACHE: dict = {{}}  # {context[:40]}",
        "docs": f'"""\\n{context[:80]}\\n"""',
        "style": f"# style: formatted at {ts}",
        "ci": f"# ci: updated at {ts}",
        "chore": f"# chore: {context[:60]}",
    }
    return snippets.get(commit_type, f"# {context[:80]}")


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--day",     type=int, required=True)
    parser.add_argument("--commits", type=int, default=25)
    parser.add_argument("--plan",    type=str, required=True)
    args = parser.parse_args()

    target = max(15, min(30, args.commits))
    plan = load_plan(args.plan)
    day_plan = get_day_plan(plan, args.day)
    phase = get_phase(plan, args.day)

    print(f"\n{'='*58}")
    print(f"  Smart Health MLOps — Day {args.day}/30  (FREE TIER)")
    print(f"  Target commits : {target}")
    print(f"  API backend    : GitHub Models (gpt-4o-mini, free)")
    print(f"  API cost       : $0.00")
    print(f"{'='*58}")
    print(f"\n📋 {day_plan['title']}")
    print(f"   {day_plan['focus']}")

    made = 0

    # ── Step 1: AI-generated code for key files (up to 6 API calls) ──
    ai_budget = min(6, len(day_plan.get("files_to_create", [])))
    made += strategy_ai_generated(day_plan, phase, ai_budget)
    print(f"\n  After AI commits  : {made}/{target}")

    # ── Step 2: Task-based commits from the plan ──
    task_target = min(target - made, len(day_plan.get("commit_tasks", [])))
    made += strategy_task_commits(day_plan, made, made + task_target)
    print(f"  After task commits: {made}/{target}")

    # ── Step 3: Filler to hit exact target ──
    if made < target:
        made += strategy_filler(made, target, args.day, day_plan)

    # ── Summary file ──
    Path(".automation_state").mkdir(exist_ok=True)
    summary = {
        "day": args.day,
        "title": day_plan["title"],
        "commits_made": made,
        "target": target,
        "api_calls_used": ai_budget,
        "api_cost_usd": 0.0,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    spath = f".automation_state/day_{args.day:02d}_summary.json"
    Path(spath).write_text(json.dumps(summary, indent=2))
    commit(f"chore: add day {args.day} run summary", [spath])

    print(f"\n{'='*58}")
    print(f"  ✅  Day {args.day} done!  Commits: {made}  Cost: $0.00")
    print(f"{'='*58}\n")


if __name__ == "__main__":
    main()
